const animeList = [
  {
    _id: 1,
    type: "SERIES",
    anime: "One Piece",
    collection: "ONE_PIECE",
    genre: "Action , Adventure , Comedy , Drama , Fantasy , Shounen",
    released: "1999",
    description:
      "Gold Roger was known as the 'Pirate King,' the strongest and most infamous being to have sailed the Grand Line. The capture and execution of Roger by the World Government brought a change throughout the world. His last words before his death revealed the existence of the greatest treasure in the world, One Piece. It was this revelation that brought about the Grand Age of Pirates, men who dreamed of finding One Piece—which promises an unlimited amount of riches and fame—and quite possibly the pinnacle of glory and the title of the Pirate King. Enter Monkey Luffy, a 17-year-old boy who defies your standard definition of a pirate. Rather than the popular persona of a wicked, hardened, toothless pirate ransacking villages for fun, Luffy's reason for being a pirate is one of pure wonder: the thought of an exciting adventure that leads him to intriguing people and ultimately, the promised treasure. Following in the footsteps of his childhood hero, Luffy and his crew travel across the Grand Line, experiencing crazy adventures, unveiling dark mysteries and battling strong enemies, all in order to reach the most coveted of all fortunes—One Piece. [Written by MAL Rewrite]",
    totalEpisodes: 1122,
    dubbedEpisodes: 1100,
    subbedEpisodes: 1122,
    slug: "/one-piece-100/{{ep}}",
    image: "/anime/one-piece.webp",
    filers: [626, 627, 628, 747, 748, 749, 750, 780, 781, 782, 895, 896, 807, 1029, 1030],
    cat: ["sub", "dub"],
  },
  {
    _id: 2,
    type: "SERIES",
    anime: "One Piece Log Fish Man Island Saga",
    collection: "ONE_PIECE",
    genre: "Action , Adventure , Fantasy , Shounen",
    released: "2024",
    description: "",
    totalEpisodes: 18,
    dubbedEpisodes: 0,
    subbedEpisodes: 18,
    slug: "/one-piece-log-fish-man-island-saga-19404/{{ep}}",
    image: "https://www11.gogoanime.me/cover/one-piece-gyojin-tou-hen.png",
    filers: [],
    cat: ["sub"],
  },
  {
    _id: 3,
    type: "SERIES",
    anime: "Dragon Ball Daima",
    collection: "DRAGON_BALL",
    genre: "Action , Adventure , Comedy , Fantasy , Martial Arts , Shounen , Super Power",
    released: "2024",
    description:
      "Gold Roger was known as the 'Pirate King,' the strongest and most infamous being to have sailed the Grand Line. The capture and execution of Roger by the World Government brought a change throughout the world. His last words before his death revealed the existence of the greatest treasure in the world, One Piece. It was this revelation that brought about the Grand Age of Pirates, men who dreamed of finding One Piece—which promises an unlimited amount of riches and fame—and quite possibly the pinnacle of glory and the title of the Pirate King. Enter Monkey Luffy, a 17-year-old boy who defies your standard definition of a pirate. Rather than the popular persona of a wicked, hardened, toothless pirate ransacking villages for fun, Luffy's reason for being a pirate is one of pure wonder: the thought of an exciting adventure that leads him to intriguing people and ultimately, the promised treasure. Following in the footsteps of his childhood hero, Luffy and his crew travel across the Grand Line, experiencing crazy adventures, unveiling dark mysteries and battling strong enemies, all in order to reach the most coveted of all fortunes—One Piece. [Written by MAL Rewrite]",
    totalEpisodes: 20,
    dubbedEpisodes: 0,
    subbedEpisodes: 20,
    slug: "/dragon-ball-daima-19328/{{ep}}",
    image: "https://www11.gogoanime.me/cover/dragon-ball-daima.png",
    filers: [],
    cat: ["sub"],
  },
  {
    _id: 4,
    type: "SERIES",
    anime: "Jujutsu Kaisen",
    collection: "JUJUTSU_KAISEN",
    genre: "Action , Demons , Horror , School , Shounen , Supernatural",
    released: "2023",
    description: "Jujutsu Kaisen 2nd Season (Dub) [Written by MAL Rewrite]",
    totalEpisodes: 24,
    dubbedEpisodes: 24,
    subbedEpisodes: 24,
    slug: "/jujutsu-kaisen-tv-534/{{ep}}",
    image: "https://www11.gogoanime.me/cover/jujutsu-kaisen-tv.png",
    filers: [],
    cat: ["sub", "dub"],
  },
  {
    _id: 5,
    type: "SERIES",
    anime: "Jujutsu Kaisen 2nd Season",
    collection: "JUJUTSU_KAISEN",
    genre: " Action , Dub , Fantasy , School , Shounen",
    description: "Jujutsu Kaisen 2nd Season (Dub) [Written by MAL Rewrite]",
    totalEpisodes: 23,
    dubbedEpisodes: 23,
    subbedEpisodes: 23,
    slug: "/jujutsu-kaisen-2nd-season-18413/{{ep}}",
    image: "https://www11.gogoanime.me/cover/jujutsu-kaisen-2nd-season-dub.png",
    filers: [],
    cat: ["sub", "dub"],
  },
  {
    _id: 6,
    type: "MOVIE",
    anime: "Jujutsu Kaisen 0",
    collection: "JUJUTSU_KAISEN",
    genre: "Action , Fantasy , School , Shounen",
    released: "2021",
    description: "Jujutsu Kaisen 2nd Season (Dub) [Written by MAL Rewrite]",
    totalEpisodes: 1,
    dubbedEpisodes: 1,
    subbedEpisodes: 1,
    slug: "/jujutsu-kaisen-tv-534/{{ep}}",
    image: "https://www11.gogoanime.me/cover/jujutsu-kaisen-0-dub.png",
    filers: [],
    cat: ["sub", "dub"],
  },
  {
    _id: 7,
    type: "MOVIE",
    anime: "Super Dragon Ball Heroes Meteor Mission",
    collection: "JUJUTSU_KAISEN",
    genre: "Action , Adventure , Martial Arts , Shounen",
    released: "2023",
    description:
      "The Demon Invader Saga (魔の侵略者編 Ma no Shinryakusha Hen, lit. 'Demon Invader Arc') is the ninth original saga of Dragon Ball Heroes. It continues on from where the Supreme Kai of Time Saga of Super Dragon Ball Heroes left off.",
    totalEpisodes: 1,
    dubbedEpisodes: 1,
    subbedEpisodes: 1,
    slug: "/super-dragon-ball-heroes-meteor-mission-534/{{ep}}",
    image: "https://www11.gogoanime.me/cover/super-dragon-ball-heroes-meteor-mission.png",
    filers: [],
    cat: ["sub", "dub"],
  },
  {
    _id: 8,
    type: "SERIES",
    anime: "Boruto Naruto Next Generations",
    collection: "NARUTO",
    genre: "Action , Adventure , Martial Arts , Shounen , Super Power",
    released: "2017",
    description:
      "Naruto was a young shinobi with an incorrigible knack for mischief. He achieved his dream to become the greatest ninja in the village and his face sits atop the Hokage monument. But this is not his story... A new generation of ninja are ready to take the stage, led by Naruto's own son, Boruto!",
    totalEpisodes: 293,
    dubbedEpisodes: 293,
    subbedEpisodes: 293,
    slug: "boruto-naruto-next-generations-8143/{{ep}}",
    image: "https://www11.gogoanime.me/cover/boruto-naruto-next-generations.png",
    filers: [],
    cat: ["sub", "dub"],
  },
];

export default animeList;
